version: '3.8'

# Central Gateway - Operational & Monitoring Tools
# Standalone deployment for Central Gateway only

services:
  # Central MCP Gateway (Zendesk, Splunk, New Relic, Memory)
  central-gateway:
    build:
      context: ./mock_services/central_gateway
    ports:
      - "8083:8083"
    volumes:
      - ./data/mock_tickets:/data/mock_tickets:ro
    environment:
      - LOG_LEVEL=INFO
      - MOCK_TICKETS_DIR=/data/mock_tickets
    networks:
      - support-template-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  support-template-network:
    name: support-template-network
    driver: bridge

volumes:
  mock_tickets:
    driver: local

