version: '3.8'

services:
  # LangFuse Server
  langfuse:
    image: langfuse/langfuse:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - SALT=your-salt-here
      - ENCRYPTION_KEY=your-encryption-key-here
    depends_on:
      - postgres
      - clickhouse
    networks:
      - langfuse-network

  # PostgreSQL for LangFuse metadata
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - langfuse-network

  # ClickHouse for LangFuse data storage
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8124:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_DB: langfuse
      CLICKHOUSE_USER: langfuse
      CLICKHOUSE_PASSWORD: langfuse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - langfuse-network

volumes:
  postgres_data:
  clickhouse_data:

networks:
  langfuse-network:
    driver: bridge
